<?php
/*
 * =================================================================================
 *
 * FULL LENGTH LISTS
 * All the length options sourced from @link http://www.kylesconverter.com/length/
 *
 * =================================================================================
 */

$full_length_options = array(
    'angstroms'             => array( 'A measure of the wavelength of visible light, UV light, X rays, and gamma rays. Superseded these days by the nanometer.', '' ),
    'arpents'               => array( '', 'https://en.wikipedia.org/wiki/Arpent' ),
    'cables (Imperial)',
    'cables (International)',
    'cables (US)',
    'centimeters',
    'chains',
    'cubits',
    'decameters',
    'decimeters', 
    'ells',
    'fathoms',
    'feet',
    'feet (French)',
    'feet (US Survey)',
    'fingers',
    'fingers (cloth)',
    'French',
    'furlongs',
    'gigameters',
    'hands',
    'inches',
    'kilofeet',
    'kilometers',
    'leagues',
    'leagues (land)',
    'light-days',
    'light-hours',
    'light-minutes',
    'light-seconds',
    'light-years',
    'lines','links',
    'marathons',
    'megameters',
    'meters',
    'metric feet',
    'metric inches',
    'metric miles',
    'Mickeys',
    'microinches',
    'micrometers',
    'microns',
    'mils',
    'miles',
    'millimeters',
    'myriameters',
    'nails (cloth)',
    'nanometers',
    'nautical leagues',
    'nautical miles',
    'paces',
    'palms',
    'parsecs',
    'perches',
    'picas',
    'picometers',
    'points',
    'quarters',
    'rods',
    'ropes',
    'shaku',
    'smoots',
    'spans',
    'steps',
    'terameters',
    'twips',
    'yards'
);